#
# addon kiali
#
enabled: false
replicaCount: 1
hub: docker.io/kiali
tag: v0.17
contextPath: /
proxy:
  repository: rancher/nginx
  tag: 1.15.8-alpine
nodeSelector: {}

# Specify the pod anti-affinity that allows you to constrain which nodes
# your pod is eligible to be scheduled based on labels on pods that are
# already running on the node rather than based on labels on nodes.
# There are currently two types of anti-affinity:
#    "requiredDuringSchedulingIgnoredDuringExecution"
#    "preferredDuringSchedulingIgnoredDuringExecution"
# which denote “hard” vs. “soft” requirements, you can define your values
# in "podAntiAffinityLabelSelector" and "podAntiAffinityTermLabelSelector"
# correspondingly.
# For example:
# podAntiAffinityLabelSelector:
# - key: security
#   operator: In
#   values: S1,S2
#   topologyKey: "kubernetes.io/hostname"
# This pod anti-affinity rule says that the pod requires not to be scheduled
# onto a node if that node is already running a pod with label having key
# “security” and value “S1”.
podAntiAffinityLabelSelector: {}
podAntiAffinityTermLabelSelector: {}

ingress:
  enabled: false
  ## Used to create an Ingress record.
  hosts:
    - kiali.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: kiali-tls
    #   hosts:
    #     - kiali.local

dashboard:
  # login/anonymous
  authStrategy: anonymous
  secretName: kiali
  username: admin
  passphrase: admin

  # Override the automatically detected Grafana URL, useful when Grafana service has no ExternalIPs
  grafanaURL:

  # Override the automatically detected Jaeger URL, useful when Jaeger service has no ExternalIPs
  jaegerURL:
  grafanaDisplayLink: "false"
prometheusAddr: http://prometheus:9090

service:
  type: ClusterIP

resources: {}