{{- $kubeletSvcName := "expose-kubelets-metrics" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $kubeletSvcName }}
  labels:
    k8s-app: kubelet
    {{ .Values.apiGroup }}: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    targetPort: 10250

---
apiVersion: {{ template "deployment_api_version" . }}
kind: Deployment
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: prometheus-operator
          image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --kubelet-service={{ .Release.Namespace }}/{{ $kubeletSvcName }}
            - --log-format={{ .Values.logFormat }}
            - --log-level={{ .Values.logLevel }}
            - --prometheus-config-reloader={{ template "system_default_registry" . }}{{ .Values.image.prometheusConfigReloader.repository }}:{{ .Values.image.prometheusConfigReloader.tag }}
            - --config-reloader-image={{ template "system_default_registry" . }}{{ .Values.image.configmapReload.repository }}:{{ .Values.image.configmapReload.tag }}
            - --labels={{ .Values.apiGroup }}=true
            - --crd-apigroup={{ template "operator_api_group" . }}
            - --manage-crds={{ .Values.manageCRDs }}
            - --with-validation={{ .Values.withValidation }}
          ports:
          - containerPort: 8080
            name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
        beta.kubernetes.io/os: linux
        {{- range .Values.nodeSelectors }}
        {{- $pair := regexSplit "=" . 2 }}
        {{- if eq 2 (len $pair) }}
        {{ (index $pair 0) }}: {{ (index $pair 1) }}
        {{- else }}
        {{ (index $pair 0) }}: ""
        {{- end }}
        {{- end }}
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ default (include "app.fullname" .) .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
