apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        service: "jaeger-query"
        {{- if .Values.dashboard.jaegerURL }}
        url: {{ .Values.dashboard.jaegerURL }}
        {{- end }}
      grafana:
        custom_metrics_url: "http://prometheus.{{ .Release.Namespace }}:9090"
        {{- if .Values.dashboard.grafanaURL }}
        url: {{ .Values.dashboard.grafanaURL }}
        {{- else }}
        url: "http://prometheus.{{ .Release.Namespace }}:9090"
        {{- end }}
