apiVersion: v1
appVersion: "0.1.3"
description: |
  Run CIS benchmark tests
name: rancher-cis-benchmark
version: 0.1.3
home: https://github.com/rancher/system-charts/charts/rancher-cis-benchmark
sources:
  - "https://github.com/rancher/system-charts/charts/rancher-cis-benchmark"
maintainers:
  - name: Murali Paluru
    email: leodotcloud@gmail.com
