apiVersion: v1
name: operator-init
version: 0.1.0
appVersion: 0.1.0
tillerVersion: ">=2.7.2-0"
description: Helm chart to initialize Prometheus Operator CRDs
keywords:
  - prometheus-operator
  - crd
maintainers:
- name: support
  email: support@rancher.com
engine: gotpl
