apiVersion: v1
appVersion: "0.9.0"
description: A Helm chart for Rancher global monitoring
name: rancher-thanos
version: 0.0.1
keywords:
  - thanos
  - prometheus
  - metrics
sources:
  - https://github.com/thanos-io/thanos
icon: file://../thanos-logo.png
maintainers:
- name: Lawrence Li
  email: lawrence@rancher.com
