apiVersion: v1
name: rancher-k3s-upgrader
description: Enables a k3s cluster to update itself by reacting to Plan CRs.
home: https://github.com/rancher/system-charts/charts/system-upgrade-controller
sources:
  - "https://github.com/rancher/system-charts/charts/system-upgrade-controller"
version: 0.1.0
appVersion: v0.3.1
