#
# addon prometheus configuration
#
enabled: true
replicaCount: 1

repository: docker.io/prom/prometheus
tag: v2.3.1
proxy:
  repository: rancher/nginx
  tag: 1.15.8-alpine

retention: 6h
nodeSelector: {}

# Controls the frequency of prometheus scraping
scrapeInterval: 15s

contextPath: /prometheus

ingress:
  enabled: false
  ## Used to create an Ingress record.
  hosts:
    - prometheus.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: prometheus-tls
    #   hosts:
    #     - prometheus.local

service:
  annotations: {}
  type: ClusterIP
security:
  enabled: true

resources: {}