apiVersion: v1
description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
engine: gotpl
maintainers:
- name: thxCode
  email: frank@rancher.com
name: rancher-monitoring
sources:
- https://github.com/coreos/prometheus-operator
version: 0.1.5
appVersion: 0.1.5
home: https://github.com/coreos/prometheus-operator
keywords:
- operator
- prometheus
icon: https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png
kubeVersion: "< 1.22.0-0"
