apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.nginx.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: nginx
data:
  copy-datasource-plugin-json.sh: |-
    #!/bin/bash

    srcpath="/usr/share/grafana/public/app/plugins/datasource/prometheus/plugin.json"
    dstpath="/host/grafana/raw-plugin.json"

    if [[ -f $srcpath ]] && [[ -d /host ]]; then
      mkdir -p /host/grafana
      cp -f $srcpath $dstpath

      exit 0
    fi

    exit 1

  modify-datasource-plugin-json.sh: |-
    #!/bin/sh

    srcpath="/host/grafana/raw-plugin.json"
    dstpath="/host/grafana/plugin.json"

    if [ -f $srcpath ] && [ -d /host ]; then
      mkdir -p /host/grafana

      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

      cat $srcpath | K8S_BEARERTOKEN="Bearer $token" jq 'to_entries | . + [{"key":"routes","value":[{"path":"api/v1","url":"{{ .Values.prometheusDatasourceURL }}/api/v1","headers":[{"name":"Authorization","content":env.K8S_BEARERTOKEN}]}]}] | from_entries' > $dstpath

      exit 0
    fi

    exit 1
  
  nginx.conf: |-
    user                  nginx;
    worker_processes      auto;
    error_log             /dev/stdout warn;
    pid                   /var/run/nginx.pid;

    events {
       worker_connections 1024;
    }

    http {
      include       /etc/nginx/mime.types;
      log_format    main '[$time_local - $status] $remote_addr - $remote_user $request ($http_referer)';

      proxy_connect_timeout       10;
      proxy_read_timeout          180;
      proxy_send_timeout          5;
      proxy_buffering             off;
      proxy_cache_path            /tmp/nginx levels=1:2 keys_zone=my_zone:100m inactive=1d max_size=10g;

      server {
        listen          80;
        access_log      off;

        gzip            on;
        gzip_min_length 1k;
        gzip_comp_level 2;
        gzip_types      text/plain application/javascript application/x-javascript text/css application/xml text/javascript image/jpeg image/gif image/png;
        gzip_vary       on;
        gzip_disable    "MSIE [1-6]\.";

        proxy_set_header Host $host;

        location /api/dashboards {
          proxy_pass     http://localhost:3000;
        }

        location /api/search {
          proxy_pass     http://localhost:3000;

          sub_filter_types application/json;
          sub_filter_once off;
          sub_filter '"url":"/d' '"url":"d';
        }

        location / {
          proxy_cache         my_zone;
          proxy_cache_valid   200 302 1d;
          proxy_cache_valid   301 30d;
          proxy_cache_valid   any 5m;
          proxy_cache_bypass  $http_cache_control;
          add_header          X-Proxy-Cache $upstream_cache_status;
          add_header          Cache-Control "public";
          
          proxy_pass     http://localhost:3000/;

          sub_filter_types text/html;
          sub_filter_once off;
          sub_filter '"appSubUrl":""' '"appSubUrl":"."';
          sub_filter '"url":"/' '"url":"./';
          sub_filter ':"/avatar/' ':"avatar/';

          if ($request_filename ~ .*\.(?:js|css|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm)$) {
            expires             90d;
          }
        }
      }
    }
