apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.provisionings.fullname" . }}
data:
  dashboards.yaml: |+
    - name: RANCHER_MONITORING
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 0 #never
      options:
        path: /var/lib/grafana/rancher-dashboards


  datasources.yaml: |+
    apiVersion: 1

    datasources:
    - name: RANCHER_MONITORING
      type: prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      url: {{ .Values.prometheusDatasourceURL }}