apiVersion: v1
name: rancher-gke-operator
description: A Helm chart for provisioning GKE clusters
home: https://github.com/rancher/gke-operator
sources:
  - "https://github.com/rancher/gke-operator"
version: 1.0.100
appVersion: v1.0.1-rc4
