labels: {}

image:
  repository: shanewxy/fluentd
  tag: latest
  pullPolicy: IfNotPresent

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 500Mi
  # requests:
  #   cpu: 100m
  #   memory: 200Mi
# env:

command: '["sh", "-c", "tail -f /dev/null"]'

rbac:
  create: true

serviceAccount:
  create: true

annotations: {}

# updateStrategy:
#   type: RollingUpdate

tolerations:
  - effect: NoSchedule
    operator: Exists

nodeSelector: {}