apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eksclusterconfigs.eks.cattle.io
spec:
  group: eks.cattle.io
  names:
    kind: EKSClusterConfig
    plural: eksclusterconfigs
    shortNames:
    - ekscc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            amazonCredentialSecret:
              type: string
            displayName:
              type: string
            imported:
              type: boolean
            kmsKey:
              type: string
            kubernetesVersion:
              type: string
            loggingTypes:
              items:
                type: string
              nullable: true
              type: array
            nodeGroups:
              items:
                properties:
                  desiredSize:
                    nullable: true
                    type: integer
                  diskSize:
                    nullable: true
                    type: integer
                  ec2SshKey:
                    nullable: true
                    type: string
                  gpu:
                    type: boolean
                  instanceType:
                    nullable: true
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  maxSize:
                    nullable: true
                    type: integer
                  minSize:
                    nullable: true
                    type: integer
                  nodegroupName:
                    type: string
                  subnets:
                    items:
                      type: string
                    nullable: true
                    type: array
                  tags:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  version:
                    nullable: true
                    type: string
                required:
                - nodegroupName
                - instanceType
                type: object
              nullable: true
              type: array
            privateAccess:
              type: boolean
            publicAccess:
              type: boolean
            publicAccessSources:
              items:
                type: string
              nullable: true
              type: array
            region:
              type: string
            secretsEncryption:
              type: boolean
            securityGroups:
              items:
                type: string
              nullable: true
              type: array
            serviceRole:
              type: string
            subnets:
              items:
                type: string
              nullable: true
              type: array
            tags:
              additionalProperties:
                type: string
              nullable: true
              type: object
          required:
          - amazonCredentialSecret
          - publicAccess
          - privateAccess
          - displayName
          - region
          type: object
        status:
          properties:
            failureMessage:
              type: string
            networkFieldsSource:
              type: string
            phase:
              type: string
            securityGroups:
              items:
                type: string
              nullable: true
              type: array
            subnets:
              items:
                type: string
              nullable: true
              type: array
            virtualNetwork:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
