apiVersion: v1
name: rancher-eks-operator
description: A Helm chart for provisioning EKS clusters
home: https://github.com/rancher/eks-operator
sources:
  - "https://github.com/rancher/eks-operator"
version: 1.1.100
appVersion: v1.1.1-rc5
