apiVersion: v1
name: rancher-eks-controller
description: A Helm chart for provisioning EKS clusters
home: https://github.com/rancher/system-charts/charts/eks-controller
sources:
  - "https://github.com/rancher/system-charts/charts/eks-controller"
version: 0.1.0
appVersion: v0.1.0-rc2
